### ISSUE TITLE
QWidget demo example with roscpp

### ISSUE THREAD

**Issue by bryangd34** [tu-darmstadt-ros-pkg/hector_rviz_overlay#4]
The QWidget demo in hector_rviz_overlay_demo/src/demo_overlay_display.cpp is great for seeing how to overlay a .ui created in Qt Designer.
I'm unsure though how to use roscpp with this demo so I can start, for example, publishing something on a button click.

The issue is I am not very experienced with c++. I have written nodes that publish/subscribe in c++, but combining this with the QWidget demo I have not been able to do successfully.

Any help would be much appreciated!
Thanks.

**Comment by StefanFabian** [comment]
Similar to your publish/subscribe nodes you connect the signal of the button click to a slot (function) and in that function, you publish whatever. You'll probably need to have a ros::NodeHandle and your publisher as class members of the class of the slot.
I would advise using QML if you can though, as it is a lot easier, more performant, and beginner-friendly.
I wouldn't recommend using QtWidgets to anyone really since in most use cases QML is just better.

Please note that GitHub issues are not for programming support though. I would advise you to practice more with the ROS documentation until you are comfortable with the concepts and if you encounter specific problems use platforms such as the ROS or robotics StackExchange.

**Comment by bryangd34** [comment]
Thank you @StefanFabian for your informative response.
